{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.fullnameOverride }}
  labels:
    app.kubernetes.io/instance: {{ .Values.fullnameOverride }}     
    app.kubernetes.io/managed-by: {{ .Release.Service }}                                                                                                                                                                                                     │
    app.kubernetes.io/name: {{ .Values.fullnameOverride }}    
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}    
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}  
  {{- with .Values.annotations.hpa }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.fullnameOverride }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 900
        periodSeconds: 30
      selectPolicy: Max
  metrics:
    {{- if .Values.autoscaling.averageUtilMem }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.averageUtilMem }}
    {{- end }}
    {{- if .Values.autoscaling.averageUtilCpu }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.averageUtilCpu }}
    {{- end }}
{{- end }}