apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}
  labels:
    app.kubernetes.io/instance: {{ .Values.fullnameOverride }}     
    app.kubernetes.io/managed-by: {{ .Release.Service }}                                                                                                                                                                                                     │
    app.kubernetes.io/name: {{ .Values.fullnameOverride }}    
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}    
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}  
  {{- with .Values.annotations.service }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.headless }}
  clusterIP: None
  {{- end }}
  ports:
    {{- range .Values.service.configs }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ .Values.fullnameOverride }}  
    app.kubernetes.io/instance: {{ .Values.fullnameOverride }}  