{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fullnameOverride }}
  labels:
    app.kubernetes.io/instance: {{ .Values.fullnameOverride }}     
    app.kubernetes.io/managed-by: {{ .Release.Service }}                                                                                                                                                                                                     │
    app.kubernetes.io/name: {{ .Values.fullnameOverride }}    
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}    
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}  
  {{- with .Values.annotations.serviceaccount }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

