podSecurityContext: {}
securityContext: {}
nodeSelector: {}
affinity: {}
tolerations: []

## Service/App-name
fullnameOverride: atlas

## Replica ##
replicaCount: 1

## HPA ##
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  averageUtilMem: 80
  averageUtilCpu: 80

## All Annotations ##
## Add annotation to selected resources
annotations:
  ingress:
    "nginx.ingress.kubernetes.io/proxy-body-size": "10M"
    "nginx.ingress.kubernetes.io/use-regex": "true"
    "nginx.org/client-max-body-size": "10M"
  deployment: {}
  hpa: {}
  preupgradejob:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
  service: {}
  serviceaccount: {}
  vault:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"

## in case we need hostAliases ##
hostAliases:
  enabled: true  
  iphostname:
    - ip: "8.8.8.8"
      hostnames:
      - "google.com"
    # - ip: "1.1.1.1"
    #   hostnames:
    #   - "cloudflare.com"

## Pods Lifecycle ##
gracePeriodSeconds:
  enabled: true
  value: 60

## Volumes ##
## Add google creds SA here
## google Creds names for RC is samilar with green releases
volumes: 
  # example volume from secrets
  - name: service-account
    secret:
      secretName: atlas-sa
  # example volume from pvc
  - name: data
    persistentVolumeClaim:
      claimName: volumes-pvc
volumeMounts:
  # example volume from secrets
  - name: service-account
    mountPath: /mnt
  # example volume from pvc
  - name: data
    mountPath: /data

## Migration ##
migrations:
  enabled: false
  # type: pre-upgrade-job
  type: init-container
    # Init Container 
    # - "cd /go/src/atlas && ./main db:migrate"
    # Pre-Uprade-Job 
    # - "cd /opt/atlas ; envsubst < config/app.yaml.dist > config/app.yaml ; ./atlas db:migrate up"
  args:
    - "echo 'Initializing Service...'"
    # - "cd /opt/atlas ; ./atlas db:migrate up"

## This is default imagePullSecret
imagePullSecrets:
  - name: "gcr-json-key"
image:
  pullPolicy: "IfNotPresent"
  repository: "asia.gcr.io/manuyafsya/atlas/apps" # {"$imagepolicy": "flux-system:apps:name"}
  tag: "1.0.0" # {"$imagepolicy": "flux-system:aggregator:tag"}

## Use interceptor to build env and run the entrypoint command (Read Dockerfile)
interceptor:
  enabled: false
  args: "echo 'test-interceptor'"

service:
  enabled: false
  type: ClusterIP
  configs:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
    - name: grpc
      port: 80
      targetPort: 8000
      protocol: TCP
    # - name: http
    #   port: 3000
    #   targetPort: 3000
    #   protocol: TCP
  # Headless to load balance grpc service that have more than one pods
  headless: false

## liveness type httpGet, exec, tcpSocket
## httpGet require path
## exec for gRPC
## tcpSocket not require path
liveness:
  port: 8000
  type: tcpSocket
  path: /
  initialDelay: 30
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

## check TRD to setup resource
resources: 
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 300m
    memory: 192Mi

## Secret ##
secrets:
  configs:
    enabled: false
    autorestart:
      enabled: false
    path: pathto/configs/atlas
  creds:
    enabled: false
    autorestart:
      enabled: false
    path: pathto/creds/atlas
  additional:
    enabled: false
    name: {}